### ISSUE TITLE
Add basic Notebook usage instructions before section 3

### ISSUE THREAD

**Issue by guimou** [rh-aiservices-bu/parasol-insurance#12]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by erwangranger** [comment]
Yes, probably the fastest way. Thanks for volunteering!

**Comment by rcarrata** [comment]
@erwangranger ready to review and merge with PR https://github.com/rh-aiservices-bu/parasol-insurance/pull/42
