### ISSUE TITLE
Suggestion: Don't use web terminal to deploy argocd use (+) instead

### ISSUE THREAD

**Issue by alexgroom** [rh-aiservices-bu/parasol-insurance#124]
**Describe the bug**
As a suggestion: effort is required in section 5.2/5.3 of the lab guide to get access to the OCP web terminal. Have you considered just using the (+) in the web console to just drop yaml into and deploy/start argocd? The two drops of yaml could be processed this way instead of needing the CLI and having to introduce oc apply.

When it comes to waiting for the app to be ready, you could direct the user to the Networking | Routes web page and wait for the ic-app route to appear. 

This would simplify the guide and reduce the dependancies of the lab of systems and you wouldn't need to install the Web terminal operator.

**Comment by guimou** [comment]
fixed by #182
