### ISSUE TITLE
Parasol Insurance AI Workshop - Share - UI Issue

### ISSUE THREAD

**Issue by antowaddle** [rh-aiservices-bu/parasol-insurance#134]
**Describe the bug**
When you click to share the Parasol Insurance AI Workshop a pop-up window appears, when the end user expands this window (by dragging the icon bottom right of the window) the text box overlaps the pop-up window.

**To Reproduce**
1. Login to the Console
2. Find the Parasol Insurance UI Workspace
3. Click Share
4. Drag the icon bottom right of the window to the bottom of the screen

**Expected behavior**

**Screenshots**
![Pasted Graphic](https://github.com/user-attachments/assets/7da00855-ea19-4767-a952-295f77146f1c)

**Additional context**

**Comment by guimou** [comment]
Not related to the workshop, but to the demo system UI.
I suggest giving a feedback through the button on the top right.

**Comment by antowaddle** [comment]
Raised as feedback on the Parasol Demo site.
