### ISSUE TITLE
Solution Support: Service Level - UX Issue

### ISSUE THREAD

**Issue by antowaddle** [rh-aiservices-bu/parasol-insurance#135]
**Describe the bug**
In the 'Help' section there is a dropdown of items to assist end users. The 'Solution Support Service Level' is the only item that (when clicked) does not open a New Tab but instead launches directly in the browser. Is this expected? If the user is working on any items in the browser when they click this icon that work is lost.

Also, because the text is so long and truncates, the New Tab icon does not display and causes further confusion. 

**To Reproduce**
1. Click Help
2. Click the 'Solution Support Service Level' option 

**Expected behavior**
I'm not sure what is expected, but the behaviour of this menu item is inconsistent with the other items in the Help dropdown

**Screenshots**
![Pasted Graphic 1](https://github.com/user-attachments/assets/37e4c231-e145-4a0f-a833-b8023f30ce2f)

**Additional context**

**Comment by guimou** [comment]
Not related to the workshop, but to the demo system UI.

**Comment by antowaddle** [comment]
Raised as feedback on the Parasol Demo site.
