### ISSUE TITLE
Export to CSV - Duplicate 'Use Case' tabs

### ISSUE THREAD

**Issue by antowaddle** [rh-aiservices-bu/parasol-insurance#136]
**Describe the bug**
When exporting to CSV there are duplicate 'Use Case' tabs

**To Reproduce**
1. Click 'Catalog'
2. Then, click the 'Export to CSV' Icon

**Expected behavior**
Tabs should not be duplicated

**Screenshots**
![image](https://github.com/user-attachments/assets/a1688246-23f5-4ff9-a230-4038a2c781a0)
![Pasted Graphic 3](https://github.com/user-attachments/assets/eaf25c2f-6775-4c58-9399-9d233491319b)

**Additional context**

**Comment by guimou** [comment]
Not related to the Parasol workshop but to the demo system UI.

**Comment by antowaddle** [comment]
Raised as feedback on the Parasol Demo site.
