### ISSUE TITLE
Export to CSV - items sorted or searched do not appear in downloaded CSV

### ISSUE THREAD

**Issue by antowaddle** [rh-aiservices-bu/parasol-insurance#137]
**Describe the bug**
A default list of all catalog items appears when exporting to csv, this is regardless of the search performed by the end user. 

**To Reproduce**
1. Click 'Catalog'
2. Perform a search which a custom result i.e. with one specific result or multiple
3. Then, click the 'Export to CSV' Icon

**Expected behavior**
I expected that the search results would appear once I clicked the 'Export to csv' icon, instead the default entire list of items displays

**Screenshots**
N/A

**Additional context**

**Comment by guimou** [comment]
Not related to the Parasol workshop but to the demo system UI.

**Comment by antowaddle** [comment]
Raised as feedback on the Parasol Demo site.
