### ISSUE TITLE
Catalog - Sort by Rating - items with most high ratings are not displaying first

### ISSUE THREAD

**Issue by antowaddle** [rh-aiservices-bu/parasol-insurance#138]
**Describe the bug**
When the user clicks to 'Sort by Rating' the items with most high ratings are not displaying first. 

**To Reproduce**
1. Click Catalog
2. Sort by Rating

**Expected behavior**
I expected as the end user that the highest rating items with the most (for example) 5 star ratings would display first in the search. I don't specifically know the requirements here, but I feel this is an area that could be improved. 

**Screenshots**
![Pasted Graphic 4](https://github.com/user-attachments/assets/0fd064d6-a0b3-4533-964c-1aae2f4ddce6)

**Additional context**

**Comment by guimou** [comment]
Not related to the Parasol workshop but to the demo system UI.

**Comment by antowaddle** [comment]
Raised as feedback on the Parasol Demo site.
