### ISSUE TITLE
Provisioning - Start button is displayed 

### ISSUE THREAD

**Issue by antowaddle** [rh-aiservices-bu/parasol-insurance#139]
**Describe the bug**
When you order the demo a Provisioning Status displays, I've noticed that the 'Start' icon is also enabled but when clicked it doesn't do anything (I guess by design), should it be disabled? The dropdowns above seem to suggest that only the Delete icon should be enabled

**To Reproduce**
1. Order the parasol demo
2. Click Services
3. Click the Action item

**Expected behavior**
The button doesn't function when clicked, should it be disabled?

**Screenshots**
![Pasted Graphic 5](https://github.com/user-attachments/assets/dd80539c-589d-4fdc-809a-30c1ee4235ea)
![Pasted Graphic 6](https://github.com/user-attachments/assets/a0823050-edaa-43d2-8443-118a6f9707ec)

**Additional context**

**Comment by guimou** [comment]
Not related to the Parasol workshop but to the demo system UI.

**Comment by antowaddle** [comment]
Raised as feedback on the Parasol Demo site.
