### ISSUE TITLE
OpenShift Login - inconsistent login error message

### ISSUE THREAD

**Issue by antowaddle** [rh-aiservices-bu/parasol-insurance#140]
**Describe the bug**
When logging into OpenShift, if the user provides either an incorrect Username or Password the error message references 'Login' instead of Username

**To Reproduce**
1. Login to OpenShift
2. Enter an incorrect Username or Password
3. Click Log in

**Expected behavior**
The error should be consistent with the UI which references 'Username' and not 'Login' 

**Screenshots**
![Pasted Graphic 7](https://github.com/user-attachments/assets/d31101fe-a008-43e7-8b01-3c1ca332336c)

**Additional context**

**Comment by guimou** [comment]
Not a Parasol workshop, but an OpenShift one. Which I had not noticed in the 10 years I've been using it!

**Comment by antowaddle** [comment]
https://issues.redhat.com/browse/OCPBUGS-43609
