### ISSUE TITLE
OpenShift Login - Button Validation 

### ISSUE THREAD

**Issue by antowaddle** [rh-aiservices-bu/parasol-insurance#141]
**Describe the bug**
OpenShift - the log in button can be clicked repeatably

**To Reproduce**
1. Login to OpenShift
2. Enter a valid Username and Password
3. Click the 'Log in' button repeatably 

**Expected behavior**
The login button can be clicked several times which could have negative consequences elsewhere in the application. Ideally, buttons should be unclickable once clicked initially to prevent against this behaviour. 

**Screenshots**

**Additional context**

**Comment by guimou** [comment]
OpenShift bug, not related to the Parasol Workshop
