### ISSUE TITLE
OpenShift - Import Yaml - Button placement inconsistency 

### ISSUE THREAD

**Issue by antowaddle** [rh-aiservices-bu/parasol-insurance#142]
**Describe the bug**
When importing yaml the 'Create and 'Cancel\' button appear button left of the screen, elsewhere in the application the buttons all appear top right. 

**To Reproduce**
1. Login to OpenShift
2. Projects 
3. Import Yaml

**Expected behavior**
The button placement should be consistent across the application, elsewhere in the application the buttons all appear top right of the screen. 

**Screenshots**
![Pasted Graphic 8](https://github.com/user-attachments/assets/106576fa-5ed8-4bea-a252-9a2ec4d59928)

**Additional context**

**Comment by guimou** [comment]
OpenShift bug, not related to the workshop

**Comment by antowaddle** [comment]
https://issues.redhat.com/browse/OCPBUGS-43611
