### ISSUE TITLE
OpenShift - Character Limits

### ISSUE THREAD

**Issue by antowaddle** [rh-aiservices-bu/parasol-insurance#143]
**Describe the bug**
This is a general defect to describe a general issue with character limits across OpenShift, this may already be raised but I noticed whilst going through the Parasol Demo that several fields do not have character limits. 

**To Reproduce**
1. See above, rather than raise every single area of the application that don't support Character limits, this is a more general defect to highlight an issue across the application. If required, I'm happy to spend time documenting everywhere I see this across the application. 

**Expected behavior**
Fields should have consistent character limits across the application. 

**Screenshots**
![Pasted Graphic 9](https://github.com/user-attachments/assets/7e7a6313-3f93-45cb-9394-e71234024286)

**Additional context**

**Comment by guimou** [comment]
OpenShift bug, not related to the workshop

**Comment by antowaddle** [comment]
https://issues.redhat.com/browse/OCPBUGS-43613
