### ISSUE TITLE
OpenShift - Webhook Receiver - Invalid URL's are accepted 

### ISSUE THREAD

**Issue by antowaddle** [rh-aiservices-bu/parasol-insurance#144]
**Describe the bug**
Invalid URL's are accepted when editing or creating new webhook receivers 

**To Reproduce**
1. Login to OpenShift as an Admin
2. Create or Edit a Webhook Receiver (apologies I don't have exact steps here)
3. Enter any random information for the url and enter all the other relevant information
4. Click save

**Expected behavior**
URL's should ideally be validated upon clicking save, I've noticed that this is the case in RHOAI. 

**Screenshots**
![Pasted Graphic 10](https://github.com/user-attachments/assets/6dba5218-1e9a-4474-9a6e-15ad2297adb1)

**Additional context**

**Comment by guimou** [comment]
OpenShift bug, not related to the workshop

**Comment by antowaddle** [comment]
https://issues.redhat.com/browse/OCPBUGS-43614
