### ISSUE TITLE
OpenShift - Projects - Annotations - Incorrect error message 

### ISSUE THREAD

**Issue by antowaddle** [rh-aiservices-bu/parasol-insurance#145]
**Describe the bug**
When adding annotations, specifically adding invalid values to the 'Key' or Value fields the error messages are not consistent with the value on the ui. 

**To Reproduce**
1. login to OpenShift
2. click projects - details
3. Edit annotations and enter invalid details to the Value or Key fields (note i added 100s of Japanese characters 3装行れびじ会界ヱサハ政存ひいょ済立所おへ読劇3装行れびじ会界ヱサハ政存ひいょ済立所おへ読劇3装行れびじ会界ヱサハ政存ひいょ済立所おへ読劇3装行れびじ会界ヱサハ政存ひいょ済立所おへ読劇3装行れびじ会界ヱサハ政存ひいょ済立所おへ読劇3装行れびじ会界ヱサハ政存ひいょ済立所おへ読劇3装行れびじ会界ヱサハ政存ひいょ済立所おへ読劇3装行れびじ会界ヱサハ政存ひいょ済立所おへ読劇3装行れびじ会界ヱサハ政存ひいょ済立所おへ読劇3装行れびじ会界ヱサハ政存ひいょ済立所おへ読劇3装行れびじ会界ヱサハ政存ひいょ済立所おへ読劇3装行れびじ会界ヱサハ政存ひいょ済立所おへ読劇3装行れびじ会界ヱサハ政存ひいょ済立所おへ読劇3装行れびじ会界ヱサハ政存ひいょ済立所おへ読劇3装行れびじ会界ヱサハ政存ひいょ済立所おへ読劇3装行れびじ会界ヱサハ政存ひいょ済立所おへ読劇3装行れびじ会界ヱサハ政存ひいょ済立所おへ読劇3装行れびじ会界ヱサハ政存ひいょ済立所おへ読劇3装行れびじ会界ヱサハ政存ひいょ済立所おへ読劇3装行れびじ会界ヱサハ政存ひいょ済立所おへ読劇3装行れびじ会界ヱサハ政存ひいょ済立所おへ読劇3装行れびじ会界ヱサハ政存ひいょ済立所おへ読劇3装行れびじ会界ヱサハ政存ひいょ済立所おへ読劇3装行れびじ会界ヱサハ政存ひいょ済立所おへ読劇3装行れびじ会界ヱサハ政存ひいょ済立所おへ読劇3装行れびじ会界ヱサハ政存ひいょ済立所おへ読劇

**Expected behavior**
The error messages should be consistent with the values on the ui

**Screenshots**
![image](https://github.com/user-attachments/assets/9e545fc1-d29c-44ac-bf64-de45ebf94e7f)
![Pasted Graphic 11](https://github.com/user-attachments/assets/d114f5ae-5a61-40d2-9d82-df0294ffe6c1)

**Additional context**

**Comment by guimou** [comment]
OpenShift bug, not related to the workshop

**Comment by antowaddle** [comment]
https://issues.redhat.com/browse/OCPBUGS-43615
