### ISSUE TITLE
OpenShift - Projects - Edit Annotations - Key error message references "...metadata.annotations"

### ISSUE THREAD

**Issue by antowaddle** [rh-aiservices-bu/parasol-insurance#146]
**Describe the bug**
dit Annotations - Key error message references "...metadata.annotations"

**To Reproduce**
1. Open a project
2. Click Details and Edit Annotations
3. Add a key e.g. test
4. Click save
5. Then edit the annotation and append a few letters onto the key just added and click save

**Expected behavior**
The error message displayed is not informative to the end user 

**Screenshots**
![image](https://github.com/user-attachments/assets/79ec81e9-bd32-4db5-a387-d5d72037dd12)

**Additional context**

**Comment by guimou** [comment]
OpenShift bug, not related to the workshop

**Comment by antowaddle** [comment]
https://issues.redhat.com/browse/OCPBUGS-43616
