### ISSUE TITLE
OpenShift - Projects - Search - not functioning 

### ISSUE THREAD

**Issue by antowaddle** [rh-aiservices-bu/parasol-insurance#147]
**Describe the bug**
I've struggled to get the search to return any results, I've tried multiple records using Name or Label but no results are ever returned. 

**To Reproduce**
1. Login to OpenShift
2. Click Home and then Click Search
3. See the screenshots below to see the search criteria I was using, first adding in APIRequestCount and clicking search does not return any results (although this is valid)
4. Selecting multiple resources and then searching for either Label or API doesn't seem to return any valid results
5. When you enter in a value to search and click enter, the value is also removed

**Expected behavior**
The search functionality should be useful to the end user, personally I found it very difficult to use and provide any value. 

**Screenshots**
![image](https://github.com/user-attachments/assets/02d91cc6-7b4c-4a98-9e27-aac54fa1d6c1)
![image](https://github.com/user-attachments/assets/20028880-2157-497f-abe9-dbc16d7bd698)
![image](https://github.com/user-attachments/assets/c603c5ea-df41-4b70-9599-2694fe8e3982)

**Additional context**

**Comment by guimou** [comment]
OpenShift bug, not related to the workshop

**Comment by antowaddle** [comment]
https://issues.redhat.com/browse/OCPBUGS-43617
