### ISSUE TITLE
VSCode workbench option is missing

### ISSUE THREAD

**Issue by RHRolun** [rh-aiservices-bu/parasol-insurance#155]
![image](https://github.com/user-attachments/assets/8657eeac-f3d9-492a-82ad-f62141cd927e)

**Comment by guimou** [comment]
On purpose as it's now an ootb workench.

**Comment by guimou** [comment]
In the end I put it back as I could not patch the IS to move up the Code Server image in the list.
It's the same image as the ootb one, but at the right place, with a better name.
Fixed in #179
