### ISSUE TITLE
Remove Red Hat One in the Showroom title

### ISSUE THREAD

**Issue by guimou** [rh-aiservices-bu/parasol-insurance#16]

**Comment by guimou** [comment]
@erwangranger Would this title be OK:
Red Hat Summit and Ansible Fest - OpenShift AI Unleashed: Transforming Document Processing for Maximum Efficiency!

**Comment by erwangranger** [comment]
I'd say "claims" instead of "documents".

**Comment by erwangranger** [comment]
please link to Agv Issue so we can see where this lives and how it's done. thanks.

**Comment by guimou** [comment]
PR submitted: https://github.com/rhpds/agnosticv/pull/14516
However I'm not sure you would have access to this repo

**Comment by guimou** [comment]
PR merged
