### ISSUE TITLE
more complex passwords

### ISSUE THREAD

**Issue by erwangranger** [rh-aiservices-bu/parasol-insurance#20]
change things so that the password for user1-userX are no longer just "openshift" as it always displays the scary messages. 

consider same for `minio/minio123`

**Comment by guimou** [comment]
Should be done here: https://github.com/rhpds/agnosticv/blob/4422f5ea396e356cd3f3492b00f3843cbf4e49f4/sandboxes-gpte/openshift-ai-unleashed/common.yaml#L64
Will do it once the new catalog item is created
