### ISSUE TITLE
minio error in gitops

### ISSUE THREAD

**Issue by erwangranger** [rh-aiservices-bu/parasol-insurance#29]
not sure it matters

<img width="836" alt="image" src="https://github.com/rh-aiservices-bu/parasol-insurance/assets/32554862/0b86dfc4-185f-4702-95d3-f34655f320ac">

**Comment by rcarrata** [comment]
It works in the new env shared:
![Screenshot 2024-04-16 at 17 48 18](https://github.com/rh-aiservices-bu/parasol-insurance/assets/5543225/26eaa3cf-816d-4136-b15c-513cd2bfdba9)

@erwangranger \o/ maybe a race condition?

**Comment by erwangranger** [comment]
yes, I think it's a by-product of re-running the job when gitops runs a reconciliation. we can close this.
