### ISSUE TITLE
Automate PVC creation?

### ISSUE THREAD

**Issue by RHRolun** [rh-aiservices-bu/parasol-insurance#36]
In step 5.5 they now have to create a PVC before running the pipeline, should this be automated as it doesn't highlight any RHOAI benefits and is a point of failure?

**Comment by RHRolun** [comment]
@erwangranger what do you think?

**Comment by erwangranger** [comment]
if we do, we need the instructions to really make it clear that this was pre-scripted for them. 

and that normally they'd have to do it manually.
