### ISSUE TITLE
Remove -auto from the names of the projects

### ISSUE THREAD

**Issue by guimou** [rh-aiservices-bu/parasol-insurance#5]
create projects as userx, not userx-auto.

**Comment by erwangranger** [comment]
Hey @RHRolun , I started this in this branch: https://github.com/rh-aiservices-bu/parasol-insurance/tree/fix/remove-auto 
I'm just waiting for an env to boot up to be able to confirm it can work. 
You're more familiar with the code. I only found 2 places with `-auto` in them. 

Anyways, mostly telling you I started the work on this so we don't dupe the effort.

**Comment by erwangranger** [comment]
done in #30 . Confirmed that it seemed to work ok.
