### ISSUE TITLE
Change image for model serving selection at 4.5

### ISSUE THREAD

**Issue by guimou** [rh-aiservices-bu/parasol-insurance#7]

**Comment by erwangranger** [comment]
not sure what this is. 

the serving runtime image was and remains OpenVino Serving Runtime. 
What did I miss?

**Comment by RHRolun** [comment]
The projects are currently auto-created with Multi-model serving. The suggestion was to keep it like that so there is less chance of user error, and we can still talk about single vs multi-model serving if we want.
We would then make this change in the guide: https://github.com/rh-aiservices-bu/parasol-insurance/pull/41

**Comment by erwangranger** [comment]
as discussed, them seeing both option is more in line with what they will likely often see. gives us a chance to point out options. so we're not making this change. Even if this could lead to people picking wrong, it's not that hard to pick right.
