### ISSUE TITLE
5.5: Claims are not identified by ID anymore

### ISSUE THREAD

**Issue by guimou** [rh-aiservices-bu/parasol-insurance#73]
When creating the run it says to enter the claim id. However we don't display it anymore, only in the URL.
Text must be adapted to get the ID from the ClaimDetail, or hovering over link.
Or... With new claims having been added, we can say to put it at zero to process all. <-- I think it's the best

**Comment by RHRolun** [comment]
Closed with https://github.com/rh-aiservices-bu/parasol-insurance/pull/78
