### ISSUE TITLE
2.2 - Various corrections

### ISSUE THREAD

**Issue by guimou** [rh-aiservices-bu/parasol-insurance#88]
2.2: Use numbered steps, not bullet list
2.2: 1st bullet: We don't refer to Dashboard in the user doc. From the left navigation pane, click
2.2: 3rd bullet: Change "has" to "have".
2.2: Final bullet: User lowercase "data science"

**Comment by rcarrata** [comment]
"2.2: 1st bullet: We don't refer to Dashboard in the user doc. From the left navigation pane, click" it's already included and fixed in the dev branch. Is there anything that is missing?
