### ISSUE TITLE
2.1 Add authorization screenshot when opening Jupyter

### ISSUE THREAD

**Issue by guimou** [rh-aiservices-bu/parasol-insurance#90]

**Comment by rcarrata** [comment]
already in https://rh-aiservices-bu.github.io/parasol-insurance/modules/02-03-auto-created-workbench.html with the auth screenshot.

Maybe this is already solved?

**Comment by erwangranger** [comment]
I believe it's a screenshot of this we need to add:
![image](https://github.com/rh-aiservices-bu/parasol-insurance/assets/32554862/7983cfdf-df0b-42f9-975f-1fd3c7f6ad67)
