### ISSUE TITLE
3.4 - Cell Warning

### ISSUE THREAD

**Issue by guimou** [rh-aiservices-bu/parasol-insurance#91]
A warning about an upcoming deprecation (it doesn’t affect the actual running)
/opt/app-root/lib64/python3.11/site-packages/langchain_core/_api/deprecation.py:117: LangChainDeprecationWarning: The class `langchain_community.llms.huggingface_text_gen_inference.HuggingFaceTextGenInference` was deprecated in langchain-community 0.0.21 and will be removed in 0.2.0. Use HuggingFaceEndpoint instead.
warn_deprecated(

Add something to say it's normal and ignore

**Comment by rcarrata** [comment]
related with https://github.com/rh-aiservices-bu/parasol-insurance/issues/95, if we hide the HF warnings then this warning could be also removed
